# Generated by Django 5.2.4 on 2025-08-15 15:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('messagin_service', '0004_message_owner_recipient_owner'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='mailings',
            options={'permissions': [('can_view_mailings', 'Просмотр всех рассылок.'), ('can_block_user', 'Блокировка пользователей'), ('disabling_mailings', 'Отключение рассылок')], 'verbose_name': 'Рассылка', 'verbose_name_plural': 'Рассылки'},
        ),
        migrations.AlterModelOptions(
            name='message',
            options={'permissions': [('can_view_message', 'Просмотр всех сообщений')], 'verbose_name': 'Сообщение', 'verbose_name_plural': 'Сообщения'},
        ),
        migrations.AlterModelOptions(
            name='recipient',
            options={'permissions': [('can_view_client', 'Просмотр всех клиентов')], 'verbose_name': 'Клиент', 'verbose_name_plural': 'Клиенты'},
        ),
    ]
