# Generated by Django 5.2.4 on 2025-08-19 16:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('messagin_service', '0006_mailings_owner'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='mailings',
            options={'permissions': [('disabling_mailings', 'Отключение рассылок')], 'verbose_name': 'Рассылка', 'verbose_name_plural': 'Рассылки'},
        ),
    ]
