# Generated by Django 5.2.4 on 2025-08-19 18:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('messagin_service', '0007_alter_mailings_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='message',
            options={'verbose_name': 'Сообщение', 'verbose_name_plural': 'Сообщения'},
        ),
        migrations.AlterModelOptions(
            name='recipient',
            options={'verbose_name': 'Клиент', 'verbose_name_plural': 'Клиенты'},
        ),
    ]
